### ISSUE TITLE
Add OBJECT = [targetname] to the FITS headers

### ISSUE THREAD

**Issue by rashley2712** [warwick-one-metre/pipelined#4]
This seems to be a pretty standard FITS header in my experience. Even though this data is at the moment in the filename, it would be good to have it in the FITS headers too. 

It could be a parameter passed through the camera start directive. 

eg 
blue start [n] [targetname]

or a variable to define in the camera settings

eg
blue target [targetname], this could be the default 'prefix' too.

**Comment by pchote** [comment]
This will be covered by https://github.com/warwick-one-metre/camd/issues/10, so closing this one.
