### ISSUE TITLE
Add online WCS solutions 

### ISSUE THREAD

**Issue by pchote** [warwick-one-metre/pipelined#5]
1. Allocate enough space in the header for the wcs keys in `camd` to avoid having to rewrite the whole file.
2. Run astrometry.net with the know field position and size and a low cpu-limit (<= 1 sec).
3. Parse the output `.wcs`, taking only the keys that we need (not comments, history, etc).
4. Update the header of the already-saved frame.

**Comment by rashley2712** [comment]
Do you plan to compute WCS solution for every frame in a sequence?

**Comment by pchote** [comment]
If we can find the right balance between speed and reliability, then yeah.

**Comment by pchote** [comment]
Implemented for the online previews in d946b275a9d1cf553f35cf70848f8b0557adb41a.

This attempts a very quick (2 second max limit) solution for the preview, and doesn't attempt to solve the saved frames.  Those can be done with a higher-limit end-night task.
